<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Frames</name>
   <tag></tag>
   <elementGuidId>73dbfcfe-9329-46df-81cb-0b8b1af27c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.subNav > ul.navList > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Frames')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6803cbc1-fa4a-4f2f-a610-487159d7e6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../../index.html?org/openqa/selenium/Capabilities.html</value>
      <webElementGuid>b8d89301-e83e-41b3-b518-feac628ac14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>f5e3f9cd-ecf6-41ff-82ae-b0ab79832ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Frames</value>
      <webElementGuid>ea377eb3-8f08-44cb-9b68-0661dcf70d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/nav[1]/div[@class=&quot;fixedNav&quot;]/div[@class=&quot;subNav&quot;]/ul[@class=&quot;navList&quot;]/li[1]/a[1]</value>
      <webElementGuid>83a48d00-b34a-4e65-9092-b14dbc48bc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Frames')]</value>
      <webElementGuid>6456f2da-3b49-4a18-854d-68352a040d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[1]</value>
      <webElementGuid>dcf17a7e-ce1d-418a-87d5-9fb176532fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Index'])[1]/following::a[2]</value>
      <webElementGuid>9e64a007-2be4-4efe-abea-6620f76f9c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Frames'])[1]/preceding::a[1]</value>
      <webElementGuid>34eadad9-ba90-4869-a149-ac4bd697c02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Classes'])[1]/preceding::a[2]</value>
      <webElementGuid>e16ec792-6615-4e60-85c1-30d42d32fdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Frames']/parent::*</value>
      <webElementGuid>28fb4557-52c6-4368-8dba-82b833d6c5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../../index.html?org/openqa/selenium/Capabilities.html')]</value>
      <webElementGuid>95823892-c25a-4473-aac7-d71dc8c56999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>c9ce615e-4ee2-49b1-bd2b-646379207d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../../index.html?org/openqa/selenium/Capabilities.html' and (text() = 'Frames' or . = 'Frames')]</value>
      <webElementGuid>9f6e9ac0-79ee-4ab3-8530-ec5fb58aa332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
